apiVersion: v1
kind: ConfigMap
metadata:
  name: user-office-web-service-v2-config
  namespace: apps

data:
  application.properties: |-
    UserAccountActivationURL=https://users.facilities.rl.ac.uk/auth/VerifyAccount.aspx?id=
    UserAccountPasswordResetURL=https://users.facilities.rl.ac.uk/auth/ResetPassword.aspx?id=

    quarkus.rest-client.mailchimp-api.url=https://external-api.facilities.rl.ac.uk/mailchimp
    quarkus.rest-client.merge-user-tool-api.url=https://apis.facilities.rl.ac.uk/users/merges

    DATABASE_SERVER_LATENCY_EXPIRY_MINS=60

    quarkus.otel.exporter.otlp.endpoint=http://alloy.alloy.svc.cluster.local:4317

    JWT.publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+pvKvB1qwZZmYW3Jlo9q48CKHa0Q5PCsDq6Jn2nLxKBJqc/twF+RCIrt3PvXO9aSm1SguMzra5DypGzCjUQV0X0dNzwro0SFn6cYVGYqD2lhTFQxOiwNE+ZN/oX5ZIIcjJqFMXR/FUBMIlA8jsYI5NmcwAXJaccMASD/bhu8DcV3Nbsxz5+/V2Fyswv4e6SwFtFRboKeN6BXnwOZY4f574lfxdf8LV+oLTFj5Tiyy1zTnwT20/llF6OVVFZD3pkkUegQyKf2njXGp29AO1HhAjVMN003l04lNRC94ejjsw4p0xYU0FakKYTJMIojTlJvTxHPeIhEcXFP2FYLHpx09QIDAQAB
